/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesReportes;

import InterfacesAdministración.AsisInicio;
import InterfacesAdministración.InicioAdminUsuarios;
import InterfacesAdministración.Login;
import InterfacesProveedor.*;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
//import
/**
 *
 * @author Bryan
 */
public class Grafico_ComprasVentas extends javax.swing.JFrame {

    
    // * Creates new form ContribuyentesPrincipal
    
    //JFreeChart grafico;
    public Grafico_ComprasVentas() {
        initComponents();
        panelEstadistico3.setVisible(false);
        jPaCerrarSesion.setVisible(false);
        this.setSize(1366, 773);
        panelReportesFisicos2.setVisible(false);
        InterfacesProveedor.TextPrompt buscarcomprasventas = new InterfacesProveedor.TextPrompt("Ingrese RUC del Contribuyente", txtBuscarFacturaProveedor);
    }
boolean bandera = false ;
boolean bandera1 = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  //  @SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPEncabezado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLSidimLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPaCerrarSesion = new javax.swing.JPanel();
        jBCerrarSesion = new javax.swing.JButton();
        jPMod3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnSalirProveedor3 = new javax.swing.JButton();
        btnReportesFisicos3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        panelEstadistico3 = new javax.swing.JPanel();
        btnPagarDeclaracion3 = new javax.swing.JButton();
        btnEstadisticasComprasVentas11 = new javax.swing.JButton();
        btnCompradoProveedor3 = new javax.swing.JButton();
        btnVendidoCliente3 = new javax.swing.JButton();
        btnReporteEstadistico = new javax.swing.JButton();
        panelReportesFisicos2 = new javax.swing.JPanel();
        btnEstadisticasComprasVentas22 = new javax.swing.JButton();
        btnEstadisticasComprasVentas23 = new javax.swing.JButton();
        btnEstadisticasComprasVentas4 = new javax.swing.JButton();
        btnEstadisticasComprasVentas24 = new javax.swing.JButton();
        btnEstadisticasComprasVentas25 = new javax.swing.JButton();
        btnEstadisticasComprasVentas26 = new javax.swing.JButton();
        txtBuscarFacturaProveedor = new javax.swing.JTextField();
        btnBuscarFacturaProveedor = new javax.swing.JButton();
        btnMostrarGraficoVentasCompras = new javax.swing.JButton();
        panelGraficoVentas = new javax.swing.JPanel();
        lblGrafico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPEncabezado.setBackground(new java.awt.Color(54, 112, 171));

        jLabel2.setBackground(new java.awt.Color(80, 125, 180));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 241));
        jLabel2.setText("Hola: Admin");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLSidimLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProveedor/Logo.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPEncabezadoLayout = new javax.swing.GroupLayout(jPEncabezado);
        jPEncabezado.setLayout(jPEncabezadoLayout);
        jPEncabezadoLayout.setHorizontalGroup(
            jPEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEncabezadoLayout.createSequentialGroup()
                .addComponent(jLSidimLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPEncabezadoLayout.setVerticalGroup(
            jPEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLSidimLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(38, 35, 36));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Grafico Estadistico de Compras y Ventas");

        jPaCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));

        jBCerrarSesion.setBackground(new java.awt.Color(0, 153, 51));
        jBCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBCerrarSesion.setForeground(new java.awt.Color(240, 240, 241));
        jBCerrarSesion.setText("Cerrar Sesión");
        jBCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaCerrarSesionLayout = new javax.swing.GroupLayout(jPaCerrarSesion);
        jPaCerrarSesion.setLayout(jPaCerrarSesionLayout);
        jPaCerrarSesionLayout.setHorizontalGroup(
            jPaCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPaCerrarSesionLayout.setVerticalGroup(
            jPaCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaCerrarSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPMod3.setBackground(new java.awt.Color(51, 51, 51));
        jPMod3.setForeground(new java.awt.Color(51, 51, 51));
        jPMod3.setMaximumSize(new java.awt.Dimension(300, 200));
        jPMod3.setPreferredSize(new java.awt.Dimension(300, 280));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 241));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Reportes");

        btnSalirProveedor3.setBackground(new java.awt.Color(38, 35, 36));
        btnSalirProveedor3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalirProveedor3.setForeground(new java.awt.Color(240, 240, 241));
        btnSalirProveedor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconBack48x48.png"))); // NOI18N
        btnSalirProveedor3.setText("Volver");
        btnSalirProveedor3.setBorderPainted(false);
        btnSalirProveedor3.setFocusPainted(false);
        btnSalirProveedor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirProveedorActionPerformed(evt);
            }
        });

        btnReportesFisicos3.setBackground(new java.awt.Color(38, 35, 36));
        btnReportesFisicos3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReportesFisicos3.setForeground(new java.awt.Color(240, 240, 241));
        btnReportesFisicos3.setText("REPORTES");
        btnReportesFisicos3.setBorderPainted(false);
        btnReportesFisicos3.setFocusPainted(false);
        btnReportesFisicos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesFisicosActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosReportes/trade_report_reports_documents_2351.png"))); // NOI18N

        panelEstadistico3.setBackground(new java.awt.Color(51, 51, 51));

        btnPagarDeclaracion3.setBackground(new java.awt.Color(38, 35, 36));
        btnPagarDeclaracion3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPagarDeclaracion3.setForeground(new java.awt.Color(240, 240, 241));
        btnPagarDeclaracion3.setText("Valor a Pagar de Declaracion");
        btnPagarDeclaracion3.setBorderPainted(false);
        btnPagarDeclaracion3.setFocusPainted(false);
        btnPagarDeclaracion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarDeclaracionActionPerformed(evt);
            }
        });

        btnEstadisticasComprasVentas11.setBackground(new java.awt.Color(38, 35, 36));
        btnEstadisticasComprasVentas11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEstadisticasComprasVentas11.setForeground(new java.awt.Color(240, 240, 241));
        btnEstadisticasComprasVentas11.setText("Compras y Ventas");
        btnEstadisticasComprasVentas11.setBorderPainted(false);
        btnEstadisticasComprasVentas11.setFocusPainted(false);
        btnEstadisticasComprasVentas11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasComprasVentasActionPerformed(evt);
            }
        });

        btnCompradoProveedor3.setBackground(new java.awt.Color(38, 35, 36));
        btnCompradoProveedor3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCompradoProveedor3.setForeground(new java.awt.Color(240, 240, 241));
        btnCompradoProveedor3.setText("Total Comprado al Proveedor");
        btnCompradoProveedor3.setBorderPainted(false);
        btnCompradoProveedor3.setFocusPainted(false);
        btnCompradoProveedor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompradoProveedorActionPerformed(evt);
            }
        });

        btnVendidoCliente3.setBackground(new java.awt.Color(38, 35, 36));
        btnVendidoCliente3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVendidoCliente3.setForeground(new java.awt.Color(240, 240, 241));
        btnVendidoCliente3.setText("Total Vendido al Cliente");
        btnVendidoCliente3.setBorderPainted(false);
        btnVendidoCliente3.setFocusPainted(false);
        btnVendidoCliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendidoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEstadistico3Layout = new javax.swing.GroupLayout(panelEstadistico3);
        panelEstadistico3.setLayout(panelEstadistico3Layout);
        panelEstadistico3Layout.setHorizontalGroup(
            panelEstadistico3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadistico3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadistico3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEstadisticasComprasVentas11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCompradoProveedor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVendidoCliente3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPagarDeclaracion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEstadistico3Layout.setVerticalGroup(
            panelEstadistico3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadistico3Layout.createSequentialGroup()
                .addComponent(btnEstadisticasComprasVentas11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCompradoProveedor3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVendidoCliente3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagarDeclaracion3))
        );

        btnReporteEstadistico.setBackground(new java.awt.Color(38, 35, 36));
        btnReporteEstadistico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReporteEstadistico.setForeground(new java.awt.Color(240, 240, 241));
        btnReporteEstadistico.setText("CUADROS ESTADÍSTICOS");
        btnReporteEstadistico.setBorderPainted(false);
        btnReporteEstadistico.setFocusPainted(false);
        btnReporteEstadistico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteEstadisticoActionPerformed(evt);
            }
        });

        panelReportesFisicos2.setBackground(new java.awt.Color(51, 51, 51));

        btnEstadisticasComprasVentas22.setBackground(new java.awt.Color(38, 35, 36));
        btnEstadisticasComprasVentas22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEstadisticasComprasVentas22.setForeground(new java.awt.Color(240, 240, 241));
        btnEstadisticasComprasVentas22.setText("Clientes");
        btnEstadisticasComprasVentas22.setBorderPainted(false);
        btnEstadisticasComprasVentas22.setFocusPainted(false);
        btnEstadisticasComprasVentas22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasComprasVentas2ActionPerformed(evt);
            }
        });

        btnEstadisticasComprasVentas23.setBackground(new java.awt.Color(38, 35, 36));
        btnEstadisticasComprasVentas23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEstadisticasComprasVentas23.setForeground(new java.awt.Color(240, 240, 241));
        btnEstadisticasComprasVentas23.setText("Contribuyentes Registrados");
        btnEstadisticasComprasVentas23.setBorderPainted(false);
        btnEstadisticasComprasVentas23.setFocusPainted(false);
        btnEstadisticasComprasVentas23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasComprasVentas3ActionPerformed(evt);
            }
        });

        btnEstadisticasComprasVentas4.setBackground(new java.awt.Color(38, 35, 36));
        btnEstadisticasComprasVentas4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEstadisticasComprasVentas4.setForeground(new java.awt.Color(240, 240, 241));
        btnEstadisticasComprasVentas4.setText("Proveedores");
        btnEstadisticasComprasVentas4.setBorderPainted(false);
        btnEstadisticasComprasVentas4.setFocusPainted(false);
        btnEstadisticasComprasVentas4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasComprasVentas4ActionPerformed(evt);
            }
        });

        btnEstadisticasComprasVentas24.setBackground(new java.awt.Color(38, 35, 36));
        btnEstadisticasComprasVentas24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEstadisticasComprasVentas24.setForeground(new java.awt.Color(240, 240, 241));
        btnEstadisticasComprasVentas24.setText("Total Comprado al Proveedor");
        btnEstadisticasComprasVentas24.setBorderPainted(false);
        btnEstadisticasComprasVentas24.setFocusPainted(false);
        btnEstadisticasComprasVentas24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasComprasVentas5ActionPerformed(evt);
            }
        });

        btnEstadisticasComprasVentas25.setBackground(new java.awt.Color(38, 35, 36));
        btnEstadisticasComprasVentas25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEstadisticasComprasVentas25.setForeground(new java.awt.Color(240, 240, 241));
        btnEstadisticasComprasVentas25.setText("Total Vendido al Cliente");
        btnEstadisticasComprasVentas25.setBorderPainted(false);
        btnEstadisticasComprasVentas25.setFocusPainted(false);
        btnEstadisticasComprasVentas25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasComprasVentas8ActionPerformed(evt);
            }
        });

        btnEstadisticasComprasVentas26.setBackground(new java.awt.Color(38, 35, 36));
        btnEstadisticasComprasVentas26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEstadisticasComprasVentas26.setForeground(new java.awt.Color(240, 240, 241));
        btnEstadisticasComprasVentas26.setText("Declaraciones Realizadas");
        btnEstadisticasComprasVentas26.setBorderPainted(false);
        btnEstadisticasComprasVentas26.setFocusPainted(false);
        btnEstadisticasComprasVentas26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasComprasVentas9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReportesFisicos2Layout = new javax.swing.GroupLayout(panelReportesFisicos2);
        panelReportesFisicos2.setLayout(panelReportesFisicos2Layout);
        panelReportesFisicos2Layout.setHorizontalGroup(
            panelReportesFisicos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEstadisticasComprasVentas22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEstadisticasComprasVentas23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEstadisticasComprasVentas4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEstadisticasComprasVentas24, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
            .addComponent(btnEstadisticasComprasVentas25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelReportesFisicos2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEstadisticasComprasVentas26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelReportesFisicos2Layout.setVerticalGroup(
            panelReportesFisicos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportesFisicos2Layout.createSequentialGroup()
                .addComponent(btnEstadisticasComprasVentas23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstadisticasComprasVentas22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstadisticasComprasVentas24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstadisticasComprasVentas4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstadisticasComprasVentas25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstadisticasComprasVentas26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPMod3Layout = new javax.swing.GroupLayout(jPMod3);
        jPMod3.setLayout(jPMod3Layout);
        jPMod3Layout.setHorizontalGroup(
            jPMod3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReportesFisicos3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPMod3Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addComponent(btnReporteEstadistico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPMod3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMod3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEstadistico3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPMod3Layout.createSequentialGroup()
                        .addComponent(panelReportesFisicos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPMod3Layout.createSequentialGroup()
                .addComponent(btnSalirProveedor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPMod3Layout.setVerticalGroup(
            jPMod3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMod3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMod3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporteEstadistico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEstadistico3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnReportesFisicos3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelReportesFisicos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalirProveedor3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        txtBuscarFacturaProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBuscarFacturaProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFacturaProveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFacturaProveedorFocusLost(evt);
            }
        });

        btnBuscarFacturaProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProveedor/1490129321-rounded10_82180.png"))); // NOI18N
        btnBuscarFacturaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFacturaProveedorActionPerformed(evt);
            }
        });

        btnMostrarGraficoVentasCompras.setBackground(new java.awt.Color(38, 35, 36));
        btnMostrarGraficoVentasCompras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMostrarGraficoVentasCompras.setForeground(new java.awt.Color(240, 240, 241));
        btnMostrarGraficoVentasCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconAdd32x32.png"))); // NOI18N
        btnMostrarGraficoVentasCompras.setText("Mostrar Grafico");
        btnMostrarGraficoVentasCompras.setBorderPainted(false);
        btnMostrarGraficoVentasCompras.setFocusPainted(false);
        btnMostrarGraficoVentasCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarGraficoVentasComprasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGraficoVentasLayout = new javax.swing.GroupLayout(panelGraficoVentas);
        panelGraficoVentas.setLayout(panelGraficoVentasLayout);
        panelGraficoVentasLayout.setHorizontalGroup(
            panelGraficoVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGraficoVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGraficoVentasLayout.setVerticalGroup(
            panelGraficoVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGraficoVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPMod3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPaCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(668, 668, 668)
                        .addComponent(btnMostrarGraficoVentasCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscarFacturaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarFacturaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelGraficoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPaCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBuscarFacturaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarFacturaProveedor))
                        .addGap(18, 18, 18)
                        .addComponent(panelGraficoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrarGraficoVentasCompras)
                        .addContainerGap(72, Short.MAX_VALUE))
                    .addComponent(jPMod3, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarSesionActionPerformed
      Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBCerrarSesionActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        if(jPaCerrarSesion.isVisible())
            jPaCerrarSesion.setVisible(false);
        else jPaCerrarSesion.setVisible(true);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtBuscarFacturaProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFacturaProveedorFocusGained

    }//GEN-LAST:event_txtBuscarFacturaProveedorFocusGained

    private void txtBuscarFacturaProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFacturaProveedorFocusLost

    }//GEN-LAST:event_txtBuscarFacturaProveedorFocusLost

    private void btnBuscarFacturaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFacturaProveedorActionPerformed
        String RUC_Proveedor= "";
        if (!(txtBuscarFacturaProveedor.getText().equals("Buscar Proveedor..."))){
            RUC_Proveedor = txtBuscarFacturaProveedor.getText();

        }
    }//GEN-LAST:event_btnBuscarFacturaProveedorActionPerformed

    private void btnMostrarGraficoVentasComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarGraficoVentasComprasActionPerformed
        //String mes  = cmbMes.getSelectedItem().toString();
        String compras = "compras";
        String ventas = "ventas";
        int valorVentas = 170;
        int valorCompras = 274;
        try{
            JFreeChart grafico = null;
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ds.setValue(valorVentas, "Valor Total Ventas", "");
            ds.setValue(valorCompras, "Valor Total Compras", "");
            grafico= ChartFactory.createBarChart3D("Valor Total de Compras y Ventas","", "Valor Total", ds, PlotOrientation.VERTICAL, true, true, true);
            BufferedImage graficoBarra = grafico.createBufferedImage(panelGraficoVentas.getWidth(), panelGraficoVentas.getHeight());

        lblGrafico.setSize(panelGraficoVentas.getSize());
        lblGrafico.setIcon(new ImageIcon(graficoBarra));

        panelGraficoVentas.updateUI();
            
          /*  CategoryPlot graf = grafico.getCategoryPlot();
            graf.setRangeGridlinePaint(Color.BLUE);
            ChartPanel barPanel = new ChartPanel(grafico);
            panelGraficoVentas.removeAll();
            panelGraficoVentas.add(barPanel,BorderLayout.CENTER);
            panelGraficoVentas.validate();
            */
           /* DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ds.setValue(valorVentas, "Valor Total", "Ventas");
            ds.setValue(valorCompras, "Valor Total", "Compras");
            
            JFreeChart grafico = ChartFactory.createBarChart("Valor Total de Compras y Ventas", "", "Valor Total", ds, PlotOrientation.VERTICAL, true, true, true);
            CategoryPlot graf = grafico.getCategoryPlot();
            graf.setRangeGridlinePaint(Color.BLUE);
            ChartPanel barPanel = new ChartPanel(grafico);
            panelGraficoVentas.removeAll();
            panelGraficoVentas.add(barPanel,BorderLayout.CENTER);
            panelGraficoVentas.validate();
            */
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "no vael");
        }
        
    }//GEN-LAST:event_btnMostrarGraficoVentasComprasActionPerformed

    private void btnReporteEstadisticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteEstadisticoActionPerformed
        if (bandera ==false){
            panelEstadistico3.setVisible(true);
            bandera = true;
        }

        else{
            panelEstadistico3.setVisible(false);
            bandera = false;
        }
    }//GEN-LAST:event_btnReporteEstadisticoActionPerformed

    private void btnVendidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendidoClienteActionPerformed
        Grafico_TotalVendidoCliente notasVenta = new Grafico_TotalVendidoCliente();
        notasVenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVendidoClienteActionPerformed

    private void btnCompradoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompradoProveedorActionPerformed
        Grafico_TotalCompradoProveedor notasVenta = new Grafico_TotalCompradoProveedor();
        notasVenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCompradoProveedorActionPerformed

    private void btnEstadisticasComprasVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasComprasVentasActionPerformed
        
    }//GEN-LAST:event_btnEstadisticasComprasVentasActionPerformed

    private void btnPagarDeclaracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarDeclaracionActionPerformed
        Grafico_ValorDeclaracio credito = new Grafico_ValorDeclaracio();
        credito.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPagarDeclaracionActionPerformed

    private void btnReportesFisicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesFisicosActionPerformed
        if (bandera1 ==false){
            panelReportesFisicos2.setVisible(true);
            bandera1 = true;
        }

        else{
            panelReportesFisicos2.setVisible(false);
            bandera1 = false;
        }
    }//GEN-LAST:event_btnReportesFisicosActionPerformed

    private void btnSalirProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirProveedorActionPerformed
Login login = new Login();
        String rol = Login.rol;
        if (rol.compareTo("Administrador")==0){
            InicioAdminUsuarios A = new InicioAdminUsuarios();
            A.setVisible(true);
            this.setVisible(false);
        }
        else{
            AsisInicio A = new AsisInicio();
            A.setVisible(true);
            this.setVisible(false);
            
        }
    }//GEN-LAST:event_btnSalirProveedorActionPerformed

    private void btnEstadisticasComprasVentas9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasComprasVentas9ActionPerformed
        ReporteDeDeclaracion rdc = new ReporteDeDeclaracion();
        rdc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstadisticasComprasVentas9ActionPerformed

    private void btnEstadisticasComprasVentas8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasComprasVentas8ActionPerformed
         ReportevalorVendido rdc = new ReportevalorVendido();
        rdc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstadisticasComprasVentas8ActionPerformed

    private void btnEstadisticasComprasVentas5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasComprasVentas5ActionPerformed
      ImpuestoXFactura rdc = new ImpuestoXFactura();
        rdc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstadisticasComprasVentas5ActionPerformed

    private void btnEstadisticasComprasVentas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasComprasVentas3ActionPerformed
        ReporteDeDeclaracion rdc = new ReporteDeDeclaracion();
        rdc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstadisticasComprasVentas3ActionPerformed

    private void btnEstadisticasComprasVentas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasComprasVentas2ActionPerformed
       Clientes rdc = new Clientes();
        rdc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstadisticasComprasVentas2ActionPerformed

    private void btnEstadisticasComprasVentas4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasComprasVentas4ActionPerformed
        ReporteProveedores rdc = new ReporteProveedores();
        rdc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstadisticasComprasVentas4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafico_ComprasVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafico_ComprasVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafico_ComprasVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafico_ComprasVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafico_ComprasVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFacturaProveedor;
    private javax.swing.JButton btnCompradoProveedor3;
    private javax.swing.JButton btnEstadisticasComprasVentas11;
    private javax.swing.JButton btnEstadisticasComprasVentas22;
    private javax.swing.JButton btnEstadisticasComprasVentas23;
    private javax.swing.JButton btnEstadisticasComprasVentas24;
    private javax.swing.JButton btnEstadisticasComprasVentas25;
    private javax.swing.JButton btnEstadisticasComprasVentas26;
    private javax.swing.JButton btnEstadisticasComprasVentas4;
    private javax.swing.JButton btnMostrarGraficoVentasCompras;
    private javax.swing.JButton btnPagarDeclaracion3;
    private javax.swing.JButton btnReporteEstadistico;
    private javax.swing.JButton btnReportesFisicos3;
    private javax.swing.JButton btnSalirProveedor3;
    private javax.swing.JButton btnVendidoCliente3;
    private javax.swing.JButton jBCerrarSesion;
    private javax.swing.JLabel jLSidimLogo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPEncabezado;
    private javax.swing.JPanel jPMod3;
    private javax.swing.JPanel jPaCerrarSesion;
    private javax.swing.JLabel lblGrafico;
    private javax.swing.JPanel panelEstadistico3;
    private javax.swing.JPanel panelGraficoVentas;
    private javax.swing.JPanel panelReportesFisicos2;
    private javax.swing.JTextField txtBuscarFacturaProveedor;
    // End of variables declaration//GEN-END:variables
}
