/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesReportes;

import InterfacesAdministración.AsisInicio;
import InterfacesAdministración.InicioAdminUsuarios;
import InterfacesAdministración.Login;
import InterfacesProveedor.*;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
//import
/**
 *
 * @author Bryan
 */
public class ImpuestoXFactura extends javax.swing.JFrame {

    
    // * Creates new form ContribuyentesPrincipal
    
    //JFreeChart grafico;
    public ImpuestoXFactura() {
        initComponents();
        panelEstadistico.setVisible(false);
        jPaCerrarSesion.setVisible(false);
        this.setSize(1366, 773);
        panelReportesFisicos.setVisible(false);
        InterfacesProveedor.TextPrompt RUCProveedor = new InterfacesProveedor.TextPrompt("Ingrese el RUC del Contribuyente", txtBuscarFacturaProveedor);
    }
boolean bandera = false ;
boolean bandera1 = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  //  @SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPEncabezado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLSidimLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPaCerrarSesion = new javax.swing.JPanel();
        jBCerrarSesion = new javax.swing.JButton();
        jPMod = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnSalirProveedor = new javax.swing.JButton();
        btnReportesFisicos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelEstadistico = new javax.swing.JPanel();
        btnPagarDeclaracion = new javax.swing.JButton();
        btnEstadisticasComprasVentas = new javax.swing.JButton();
        btnCompradoProveedor = new javax.swing.JButton();
        btnVendidoCliente = new javax.swing.JButton();
        btnReporteEstadistico = new javax.swing.JButton();
        panelReportesFisicos = new javax.swing.JPanel();
        btnEstadisticasComprasVentas2 = new javax.swing.JButton();
        btnEstadisticasComprasVentas3 = new javax.swing.JButton();
        btnEstadisticasComprasVentas5 = new javax.swing.JButton();
        btnEstadisticasComprasVentas8 = new javax.swing.JButton();
        btnEstadisticasComprasVentas9 = new javax.swing.JButton();
        btnEstadisticasComprasVentas6 = new javax.swing.JButton();
        txtBuscarFacturaProveedor = new javax.swing.JTextField();
        btnBuscarFacturaProveedor = new javax.swing.JButton();
        btnMostrarGraficoVentasCompras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPEncabezado.setBackground(new java.awt.Color(54, 112, 171));

        jLabel2.setBackground(new java.awt.Color(80, 125, 180));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 241));
        jLabel2.setText("Hola: Admin");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLSidimLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProveedor/Logo.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPEncabezadoLayout = new javax.swing.GroupLayout(jPEncabezado);
        jPEncabezado.setLayout(jPEncabezadoLayout);
        jPEncabezadoLayout.setHorizontalGroup(
            jPEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEncabezadoLayout.createSequentialGroup()
                .addComponent(jLSidimLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPEncabezadoLayout.setVerticalGroup(
            jPEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLSidimLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(38, 35, 36));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Valor Total Comprado al Proveedor");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(163, 164, 166));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Aqui encuentra los Proveedores asociados a un Contribuyente");

        jPaCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));

        jBCerrarSesion.setBackground(new java.awt.Color(0, 153, 51));
        jBCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBCerrarSesion.setForeground(new java.awt.Color(240, 240, 241));
        jBCerrarSesion.setText("Cerrar Sesión");
        jBCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaCerrarSesionLayout = new javax.swing.GroupLayout(jPaCerrarSesion);
        jPaCerrarSesion.setLayout(jPaCerrarSesionLayout);
        jPaCerrarSesionLayout.setHorizontalGroup(
            jPaCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPaCerrarSesionLayout.setVerticalGroup(
            jPaCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaCerrarSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPMod.setBackground(new java.awt.Color(51, 51, 51));
        jPMod.setForeground(new java.awt.Color(51, 51, 51));
        jPMod.setMaximumSize(new java.awt.Dimension(300, 200));
        jPMod.setPreferredSize(new java.awt.Dimension(300, 280));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 241));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Reportes");

        btnSalirProveedor.setBackground(new java.awt.Color(38, 35, 36));
        btnSalirProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalirProveedor.setForeground(new java.awt.Color(240, 240, 241));
        btnSalirProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconBack48x48.png"))); // NOI18N
        btnSalirProveedor.setText("Volver");
        btnSalirProveedor.setBorderPainted(false);
        btnSalirProveedor.setFocusPainted(false);
        btnSalirProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirProveedorActionPerformed(evt);
            }
        });

        btnReportesFisicos.setBackground(new java.awt.Color(38, 35, 36));
        btnReportesFisicos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReportesFisicos.setForeground(new java.awt.Color(240, 240, 241));
        btnReportesFisicos.setText("REPORTES\n");
        btnReportesFisicos.setBorderPainted(false);
        btnReportesFisicos.setFocusPainted(false);
        btnReportesFisicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesFisicosActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosReportes/trade_report_reports_documents_2351.png"))); // NOI18N

        panelEstadistico.setBackground(new java.awt.Color(51, 51, 51));

        btnPagarDeclaracion.setBackground(new java.awt.Color(38, 35, 36));
        btnPagarDeclaracion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPagarDeclaracion.setForeground(new java.awt.Color(240, 240, 241));
        btnPagarDeclaracion.setText("Valor a Pagar de Declaracion");
        btnPagarDeclaracion.setBorderPainted(false);
        btnPagarDeclaracion.setFocusPainted(false);
        btnPagarDeclaracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarDeclaracionActionPerformed(evt);
            }
        });

        btnEstadisticasComprasVentas.setBackground(new java.awt.Color(38, 35, 36));
        btnEstadisticasComprasVentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEstadisticasComprasVentas.setForeground(new java.awt.Color(240, 240, 241));
        btnEstadisticasComprasVentas.setText("Compras y Ventas");
        btnEstadisticasComprasVentas.setBorderPainted(false);
        btnEstadisticasComprasVentas.setFocusPainted(false);
        btnEstadisticasComprasVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasComprasVentasActionPerformed(evt);
            }
        });

        btnCompradoProveedor.setBackground(new java.awt.Color(38, 35, 36));
        btnCompradoProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCompradoProveedor.setForeground(new java.awt.Color(240, 240, 241));
        btnCompradoProveedor.setText("Total Comprado al Proveedor");
        btnCompradoProveedor.setBorderPainted(false);
        btnCompradoProveedor.setFocusPainted(false);
        btnCompradoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompradoProveedorActionPerformed(evt);
            }
        });

        btnVendidoCliente.setBackground(new java.awt.Color(38, 35, 36));
        btnVendidoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVendidoCliente.setForeground(new java.awt.Color(240, 240, 241));
        btnVendidoCliente.setText("Total Vendido al Cliente");
        btnVendidoCliente.setBorderPainted(false);
        btnVendidoCliente.setFocusPainted(false);
        btnVendidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendidoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEstadisticoLayout = new javax.swing.GroupLayout(panelEstadistico);
        panelEstadistico.setLayout(panelEstadisticoLayout);
        panelEstadisticoLayout.setHorizontalGroup(
            panelEstadisticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadisticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEstadisticasComprasVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCompradoProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVendidoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPagarDeclaracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEstadisticoLayout.setVerticalGroup(
            panelEstadisticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticoLayout.createSequentialGroup()
                .addComponent(btnEstadisticasComprasVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCompradoProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVendidoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagarDeclaracion))
        );

        btnReporteEstadistico.setBackground(new java.awt.Color(38, 35, 36));
        btnReporteEstadistico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReporteEstadistico.setForeground(new java.awt.Color(240, 240, 241));
        btnReporteEstadistico.setText("CUADROS ESTADÍSTICOS");
        btnReporteEstadistico.setBorderPainted(false);
        btnReporteEstadistico.setFocusPainted(false);
        btnReporteEstadistico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteEstadisticoActionPerformed(evt);
            }
        });

        panelReportesFisicos.setBackground(new java.awt.Color(51, 51, 51));

        btnEstadisticasComprasVentas2.setBackground(new java.awt.Color(38, 35, 36));
        btnEstadisticasComprasVentas2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEstadisticasComprasVentas2.setForeground(new java.awt.Color(240, 240, 241));
        btnEstadisticasComprasVentas2.setText("Clientes");
        btnEstadisticasComprasVentas2.setBorderPainted(false);
        btnEstadisticasComprasVentas2.setFocusPainted(false);
        btnEstadisticasComprasVentas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasComprasVentas2ActionPerformed(evt);
            }
        });

        btnEstadisticasComprasVentas3.setBackground(new java.awt.Color(38, 35, 36));
        btnEstadisticasComprasVentas3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEstadisticasComprasVentas3.setForeground(new java.awt.Color(240, 240, 241));
        btnEstadisticasComprasVentas3.setText("Contribuyentes Registrados");
        btnEstadisticasComprasVentas3.setBorderPainted(false);
        btnEstadisticasComprasVentas3.setFocusPainted(false);
        btnEstadisticasComprasVentas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasComprasVentas3ActionPerformed(evt);
            }
        });

        btnEstadisticasComprasVentas5.setBackground(new java.awt.Color(38, 35, 36));
        btnEstadisticasComprasVentas5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEstadisticasComprasVentas5.setForeground(new java.awt.Color(240, 240, 241));
        btnEstadisticasComprasVentas5.setText("Total Comprado al Proveedor");
        btnEstadisticasComprasVentas5.setBorderPainted(false);
        btnEstadisticasComprasVentas5.setFocusPainted(false);
        btnEstadisticasComprasVentas5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasComprasVentas5ActionPerformed(evt);
            }
        });

        btnEstadisticasComprasVentas8.setBackground(new java.awt.Color(38, 35, 36));
        btnEstadisticasComprasVentas8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEstadisticasComprasVentas8.setForeground(new java.awt.Color(240, 240, 241));
        btnEstadisticasComprasVentas8.setText("Total Vendido al Cliente");
        btnEstadisticasComprasVentas8.setBorderPainted(false);
        btnEstadisticasComprasVentas8.setFocusPainted(false);
        btnEstadisticasComprasVentas8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasComprasVentas8ActionPerformed(evt);
            }
        });

        btnEstadisticasComprasVentas9.setBackground(new java.awt.Color(38, 35, 36));
        btnEstadisticasComprasVentas9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEstadisticasComprasVentas9.setForeground(new java.awt.Color(240, 240, 241));
        btnEstadisticasComprasVentas9.setText("Declaraciones Realizadas");
        btnEstadisticasComprasVentas9.setBorderPainted(false);
        btnEstadisticasComprasVentas9.setFocusPainted(false);
        btnEstadisticasComprasVentas9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasComprasVentas9ActionPerformed(evt);
            }
        });

        btnEstadisticasComprasVentas6.setBackground(new java.awt.Color(38, 35, 36));
        btnEstadisticasComprasVentas6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEstadisticasComprasVentas6.setForeground(new java.awt.Color(240, 240, 241));
        btnEstadisticasComprasVentas6.setText("Proveedores");
        btnEstadisticasComprasVentas6.setBorderPainted(false);
        btnEstadisticasComprasVentas6.setFocusPainted(false);
        btnEstadisticasComprasVentas6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasComprasVentas6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReportesFisicosLayout = new javax.swing.GroupLayout(panelReportesFisicos);
        panelReportesFisicos.setLayout(panelReportesFisicosLayout);
        panelReportesFisicosLayout.setHorizontalGroup(
            panelReportesFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportesFisicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReportesFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstadisticasComprasVentas2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEstadisticasComprasVentas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEstadisticasComprasVentas5, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(btnEstadisticasComprasVentas8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEstadisticasComprasVentas9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEstadisticasComprasVentas6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelReportesFisicosLayout.setVerticalGroup(
            panelReportesFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportesFisicosLayout.createSequentialGroup()
                .addComponent(btnEstadisticasComprasVentas3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstadisticasComprasVentas2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstadisticasComprasVentas5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstadisticasComprasVentas6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstadisticasComprasVentas8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstadisticasComprasVentas9)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPModLayout = new javax.swing.GroupLayout(jPMod);
        jPMod.setLayout(jPModLayout);
        jPModLayout.setHorizontalGroup(
            jPModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPModLayout.createSequentialGroup()
                .addComponent(btnSalirProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPModLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEstadistico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPModLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelReportesFisicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPModLayout.createSequentialGroup()
                .addComponent(btnReportesFisicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPModLayout.createSequentialGroup()
                .addComponent(btnReporteEstadistico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPModLayout.setVerticalGroup(
            jPModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporteEstadistico)
                .addGap(12, 12, 12)
                .addComponent(panelEstadistico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReportesFisicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelReportesFisicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalirProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        txtBuscarFacturaProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBuscarFacturaProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFacturaProveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFacturaProveedorFocusLost(evt);
            }
        });

        btnBuscarFacturaProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProveedor/1490129321-rounded10_82180.png"))); // NOI18N
        btnBuscarFacturaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFacturaProveedorActionPerformed(evt);
            }
        });

        btnMostrarGraficoVentasCompras.setBackground(new java.awt.Color(38, 35, 36));
        btnMostrarGraficoVentasCompras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMostrarGraficoVentasCompras.setForeground(new java.awt.Color(240, 240, 241));
        btnMostrarGraficoVentasCompras.setText("Generar Reporte");
        btnMostrarGraficoVentasCompras.setBorderPainted(false);
        btnMostrarGraficoVentasCompras.setFocusPainted(false);
        btnMostrarGraficoVentasCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarGraficoVentasComprasActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA", "TIPO DE COMPROBANTE DE COMPRA", "SECUENCIAL", "RUC", "PROVEEDOR", "BASE 12%", "BASE 0%", "IVA", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPMod, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPaCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                        .addComponent(btnMostrarGraficoVentasCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(387, 387, 387))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscarFacturaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarFacturaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPaCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBuscarFacturaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarFacturaProveedor))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrarGraficoVentasCompras)
                        .addContainerGap(97, Short.MAX_VALUE))
                    .addComponent(jPMod, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarSesionActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBCerrarSesionActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        if(jPaCerrarSesion.isVisible())
            jPaCerrarSesion.setVisible(false);
        else jPaCerrarSesion.setVisible(true);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnSalirProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirProveedorActionPerformed
Login login = new Login();
        String rol = Login.rol;
        if (rol.compareTo("Administrador")==0){
            InicioAdminUsuarios A = new InicioAdminUsuarios();
            A.setVisible(true);
            this.setVisible(false);
        }
        else{
            AsisInicio A = new AsisInicio();
            A.setVisible(true);
            this.setVisible(false);
            
        }
    }//GEN-LAST:event_btnSalirProveedorActionPerformed

    private void btnReportesFisicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesFisicosActionPerformed
        if (bandera1 ==false){
        panelReportesFisicos.setVisible(true);
        bandera1 = true;
    }
    
    else{
         panelReportesFisicos.setVisible(false);
        bandera1 = false;
    }

    }//GEN-LAST:event_btnReportesFisicosActionPerformed

    private void btnPagarDeclaracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarDeclaracionActionPerformed
      
    }//GEN-LAST:event_btnPagarDeclaracionActionPerformed

    private void btnEstadisticasComprasVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasComprasVentasActionPerformed
         ConsultasFacturas facturas = new ConsultasFacturas();
        facturas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstadisticasComprasVentasActionPerformed

    private void btnCompradoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompradoProveedorActionPerformed
        ConsultarNotasVenta notasVenta = new ConsultarNotasVenta();
        notasVenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCompradoProveedorActionPerformed

    private void btnVendidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendidoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVendidoClienteActionPerformed

    private void btnReporteEstadisticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteEstadisticoActionPerformed
        if (bandera ==false){
        panelEstadistico.setVisible(true);
        bandera = true;
    }
    
    else{
         panelEstadistico.setVisible(false);
        bandera = false;
    }
    }//GEN-LAST:event_btnReporteEstadisticoActionPerformed

    private void txtBuscarFacturaProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFacturaProveedorFocusGained

    }//GEN-LAST:event_txtBuscarFacturaProveedorFocusGained

    private void txtBuscarFacturaProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFacturaProveedorFocusLost

    }//GEN-LAST:event_txtBuscarFacturaProveedorFocusLost

    private void btnBuscarFacturaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFacturaProveedorActionPerformed
        String RUC_Proveedor= "";
        if (!(txtBuscarFacturaProveedor.getText().equals("Buscar Proveedor..."))){
            RUC_Proveedor = txtBuscarFacturaProveedor.getText();

        }
    }//GEN-LAST:event_btnBuscarFacturaProveedorActionPerformed

    private void btnMostrarGraficoVentasComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarGraficoVentasComprasActionPerformed
       
        
    }//GEN-LAST:event_btnMostrarGraficoVentasComprasActionPerformed

    private void btnEstadisticasComprasVentas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasComprasVentas2ActionPerformed
        Clientes rddc = new Clientes();
        rddc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstadisticasComprasVentas2ActionPerformed

    private void btnEstadisticasComprasVentas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasComprasVentas3ActionPerformed
        ReporteContribuyentes rdc = new ReporteContribuyentes();
        rdc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstadisticasComprasVentas3ActionPerformed

    private void btnEstadisticasComprasVentas5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasComprasVentas5ActionPerformed
        ImpuestoXFactura rdc = new ImpuestoXFactura();
        rdc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstadisticasComprasVentas5ActionPerformed

    private void btnEstadisticasComprasVentas8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasComprasVentas8ActionPerformed
        ReportevalorVendido ds = new ReportevalorVendido();
        ds.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstadisticasComprasVentas8ActionPerformed

    private void btnEstadisticasComprasVentas9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasComprasVentas9ActionPerformed
        ReporteDeDeclaracion ds = new ReporteDeDeclaracion();
        ds.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstadisticasComprasVentas9ActionPerformed

    private void btnEstadisticasComprasVentas6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasComprasVentas6ActionPerformed
        ReporteProveedores ds = new ReporteProveedores();
        ds.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstadisticasComprasVentas6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImpuestoXFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImpuestoXFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImpuestoXFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImpuestoXFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImpuestoXFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFacturaProveedor;
    private javax.swing.JButton btnCompradoProveedor;
    private javax.swing.JButton btnEstadisticasComprasVentas;
    private javax.swing.JButton btnEstadisticasComprasVentas2;
    private javax.swing.JButton btnEstadisticasComprasVentas3;
    private javax.swing.JButton btnEstadisticasComprasVentas5;
    private javax.swing.JButton btnEstadisticasComprasVentas6;
    private javax.swing.JButton btnEstadisticasComprasVentas8;
    private javax.swing.JButton btnEstadisticasComprasVentas9;
    private javax.swing.JButton btnMostrarGraficoVentasCompras;
    private javax.swing.JButton btnPagarDeclaracion;
    private javax.swing.JButton btnReporteEstadistico;
    private javax.swing.JButton btnReportesFisicos;
    private javax.swing.JButton btnSalirProveedor;
    private javax.swing.JButton btnVendidoCliente;
    private javax.swing.JButton jBCerrarSesion;
    private javax.swing.JLabel jLSidimLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPEncabezado;
    private javax.swing.JPanel jPMod;
    private javax.swing.JPanel jPaCerrarSesion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelEstadistico;
    private javax.swing.JPanel panelReportesFisicos;
    private javax.swing.JTextField txtBuscarFacturaProveedor;
    // End of variables declaration//GEN-END:variables
}
