/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesProveedor;


import InterfacesAdministración.AsisInicio;
import InterfacesAdministración.InicioAdminUsuarios;
import InterfacesAdministración.Login;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Bryan
 */
public class ProveedorRegistrar extends javax.swing.JFrame {

    /**
     * Creates new form ContribuyentesPrincipal
     */
    ArrayList<Proveedor> Lis;
    public ProveedorRegistrar() {
        initComponents();
        Lis = new ArrayList<Proveedor>();
        jPaCerrarSesion.setVisible(false);
        this.setSize(1366, 768);
        panelDocumentos.setVisible(false);
        TextPrompt RUCProveedor = new TextPrompt("RUC del Proveedor", txtRucProveedor);
        TextPrompt RazonProveedor = new TextPrompt("Razón Social del Proveedor", txtRazonSocialProveedor);
        TextPrompt direccionProveedor = new TextPrompt("Dirección del Proveedor", txtDireccionProveedor);
        TextPrompt correoProveedor = new TextPrompt("Correo electronico del Proveedor", txtCorreoProveedor);
        TextPrompt telefonoProveedor = new TextPrompt("Telefóno del Proveedor", txtTelefonoProveedor);
        TextPrompt contactoProveedor = new TextPrompt("Persona de Contacto del Proveedor", txtPersonaContactoProveedor);
        
    }
    
    boolean bandera = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPEncabezado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLSidimLogo = new javax.swing.JLabel();
        jPMod = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnSalirProveedor = new javax.swing.JButton();
        btnRegistrarProveedor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnListarProveedor = new javax.swing.JButton();
        btnConsultasProveedor = new javax.swing.JButton();
        panelDocumentos = new javax.swing.JPanel();
        btnNotaCredito = new javax.swing.JButton();
        btnFacturas = new javax.swing.JButton();
        btnNotaVenta = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPaCerrarSesion = new javax.swing.JPanel();
        jBCerrarSesion = new javax.swing.JButton();
        lblRucProveedor = new javax.swing.JLabel();
        txtRucProveedor = new javax.swing.JTextField();
        lblRazonSocialProveedor = new javax.swing.JLabel();
        txtRazonSocialProveedor = new javax.swing.JTextField();
        lblDireccionProveedor = new javax.swing.JLabel();
        txtDireccionProveedor = new javax.swing.JTextField();
        lblCorreoProveedor = new javax.swing.JLabel();
        txtCorreoProveedor = new javax.swing.JTextField();
        lblTelefonoProveedor = new javax.swing.JLabel();
        txtPersonaContactoProveedor = new javax.swing.JTextField();
        lblPersonaContacto = new javax.swing.JLabel();
        txtTelefonoProveedor = new javax.swing.JTextField();
        btnRegistrarProv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPEncabezado.setBackground(new java.awt.Color(54, 112, 171));

        jLabel2.setBackground(new java.awt.Color(80, 125, 180));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 241));
        jLabel2.setText("Hola: Admin");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLSidimLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProveedor/Logo.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPEncabezadoLayout = new javax.swing.GroupLayout(jPEncabezado);
        jPEncabezado.setLayout(jPEncabezadoLayout);
        jPEncabezadoLayout.setHorizontalGroup(
            jPEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEncabezadoLayout.createSequentialGroup()
                .addComponent(jLSidimLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPEncabezadoLayout.setVerticalGroup(
            jPEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLSidimLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPMod.setBackground(new java.awt.Color(51, 51, 51));
        jPMod.setForeground(new java.awt.Color(51, 51, 51));
        jPMod.setMaximumSize(new java.awt.Dimension(300, 200));
        jPMod.setPreferredSize(new java.awt.Dimension(300, 280));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 241));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Proveedores");

        btnSalirProveedor.setBackground(new java.awt.Color(38, 35, 36));
        btnSalirProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalirProveedor.setForeground(new java.awt.Color(240, 240, 241));
        btnSalirProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconBack48x48.png"))); // NOI18N
        btnSalirProveedor.setText("Volver");
        btnSalirProveedor.setBorderPainted(false);
        btnSalirProveedor.setFocusPainted(false);
        btnSalirProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirProveedorActionPerformed(evt);
            }
        });

        btnRegistrarProveedor.setBackground(new java.awt.Color(38, 35, 36));
        btnRegistrarProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarProveedor.setForeground(new java.awt.Color(240, 240, 241));
        btnRegistrarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconAdd32x32.png"))); // NOI18N
        btnRegistrarProveedor.setText("Registrar");
        btnRegistrarProveedor.setBorderPainted(false);
        btnRegistrarProveedor.setFocusPainted(false);
        btnRegistrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProveedorActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconUser48x48.png"))); // NOI18N

        btnListarProveedor.setBackground(new java.awt.Color(38, 35, 36));
        btnListarProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnListarProveedor.setForeground(new java.awt.Color(240, 240, 241));
        btnListarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconList32x32.png"))); // NOI18N
        btnListarProveedor.setText("Ver Todos");
        btnListarProveedor.setBorderPainted(false);
        btnListarProveedor.setFocusPainted(false);
        btnListarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProveedorActionPerformed(evt);
            }
        });

        btnConsultasProveedor.setBackground(new java.awt.Color(38, 35, 36));
        btnConsultasProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultasProveedor.setForeground(new java.awt.Color(240, 240, 241));
        btnConsultasProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProveedor/Consulta1.png"))); // NOI18N
        btnConsultasProveedor.setText("Consultar Documentos");
        btnConsultasProveedor.setBorderPainted(false);
        btnConsultasProveedor.setFocusPainted(false);
        btnConsultasProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasProveedorActionPerformed(evt);
            }
        });

        panelDocumentos.setBackground(new java.awt.Color(51, 51, 51));

        btnNotaCredito.setBackground(new java.awt.Color(38, 35, 36));
        btnNotaCredito.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNotaCredito.setForeground(new java.awt.Color(240, 240, 241));
        btnNotaCredito.setText("Notas de Credito");
        btnNotaCredito.setBorderPainted(false);
        btnNotaCredito.setFocusPainted(false);
        btnNotaCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotaCreditoActionPerformed(evt);
            }
        });

        btnFacturas.setBackground(new java.awt.Color(38, 35, 36));
        btnFacturas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFacturas.setForeground(new java.awt.Color(240, 240, 241));
        btnFacturas.setText("Facturas");
        btnFacturas.setBorderPainted(false);
        btnFacturas.setFocusPainted(false);
        btnFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturasActionPerformed(evt);
            }
        });

        btnNotaVenta.setBackground(new java.awt.Color(38, 35, 36));
        btnNotaVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNotaVenta.setForeground(new java.awt.Color(240, 240, 241));
        btnNotaVenta.setText("Notas de Venta");
        btnNotaVenta.setBorderPainted(false);
        btnNotaVenta.setFocusPainted(false);
        btnNotaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotaVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDocumentosLayout = new javax.swing.GroupLayout(panelDocumentos);
        panelDocumentos.setLayout(panelDocumentosLayout);
        panelDocumentosLayout.setHorizontalGroup(
            panelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDocumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDocumentosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNotaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDocumentosLayout.createSequentialGroup()
                        .addGroup(panelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNotaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDocumentosLayout.setVerticalGroup(
            panelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDocumentosLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(btnFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNotaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNotaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPModLayout = new javax.swing.GroupLayout(jPMod);
        jPMod.setLayout(jPModLayout);
        jPModLayout.setHorizontalGroup(
            jPModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrarProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnListarProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPModLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(10, 10, 10))
            .addComponent(btnSalirProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConsultasProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPModLayout.setVerticalGroup(
            jPModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultasProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalirProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jPModLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnRegistrarProveedor, btnSalirProveedor});

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(38, 35, 36));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registro Proveedor.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(163, 164, 166));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LLene el formulario para registrar un Proveedor");

        jPaCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));

        jBCerrarSesion.setBackground(new java.awt.Color(0, 153, 51));
        jBCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBCerrarSesion.setForeground(new java.awt.Color(240, 240, 241));
        jBCerrarSesion.setText("Cerrar Sesión");
        jBCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaCerrarSesionLayout = new javax.swing.GroupLayout(jPaCerrarSesion);
        jPaCerrarSesion.setLayout(jPaCerrarSesionLayout);
        jPaCerrarSesionLayout.setHorizontalGroup(
            jPaCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPaCerrarSesionLayout.setVerticalGroup(
            jPaCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaCerrarSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblRucProveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRucProveedor.setText("RUC del Proveedor:");

        txtRucProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtRucProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRucProveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRucProveedorFocusLost(evt);
            }
        });
        txtRucProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRucProveedorMouseClicked(evt);
            }
        });
        txtRucProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucProveedorActionPerformed(evt);
            }
        });

        lblRazonSocialProveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRazonSocialProveedor.setText("Razón Social:");

        txtRazonSocialProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtRazonSocialProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRazonSocialProveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRazonSocialProveedorFocusLost(evt);
            }
        });

        lblDireccionProveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDireccionProveedor.setText("Dirección:");

        txtDireccionProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDireccionProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDireccionProveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccionProveedorFocusLost(evt);
            }
        });

        lblCorreoProveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCorreoProveedor.setText("Correo Electrónico:");

        txtCorreoProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCorreoProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoProveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoProveedorFocusLost(evt);
            }
        });

        lblTelefonoProveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTelefonoProveedor.setText("Teléfono:");

        txtPersonaContactoProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPersonaContactoProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPersonaContactoProveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPersonaContactoProveedorFocusLost(evt);
            }
        });

        lblPersonaContacto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPersonaContacto.setText("Persona de Contacto:");

        txtTelefonoProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTelefonoProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoProveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoProveedorFocusLost(evt);
            }
        });

        btnRegistrarProv.setBackground(new java.awt.Color(38, 35, 36));
        btnRegistrarProv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarProv.setForeground(new java.awt.Color(240, 240, 241));
        btnRegistrarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconAdd32x32.png"))); // NOI18N
        btnRegistrarProv.setText("Registrar");
        btnRegistrarProv.setBorderPainted(false);
        btnRegistrarProv.setFocusPainted(false);
        btnRegistrarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPMod, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 537, Short.MAX_VALUE)
                                .addComponent(jPaCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRucProveedor)
                                    .addComponent(lblRazonSocialProveedor)
                                    .addComponent(lblDireccionProveedor)
                                    .addComponent(lblCorreoProveedor)
                                    .addComponent(txtCorreoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDireccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRazonSocialProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRucProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPersonaContacto)
                                    .addComponent(txtPersonaContactoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefonoProveedor)
                                    .addComponent(txtTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(btnRegistrarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPMod, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRucProveedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRucProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRazonSocialProveedor)
                                .addGap(9, 9, 9)
                                .addComponent(txtRazonSocialProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDireccionProveedor)
                                .addGap(7, 7, 7)
                                .addComponent(txtDireccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCorreoProveedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCorreoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTelefonoProveedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPersonaContacto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPersonaContactoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPaCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(btnRegistrarProv)
                        .addGap(51, 51, 51))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirProveedorActionPerformed
        Login login = new Login();
        String rol = Login.rol;
        if (rol.compareTo("Administrador")==0){
            InicioAdminUsuarios A = new InicioAdminUsuarios();
            A.setVisible(true);
            this.setVisible(false);
        }
        else{
            AsisInicio A = new AsisInicio();
            A.setVisible(true);
            this.setVisible(false);
            
        }
    }//GEN-LAST:event_btnSalirProveedorActionPerformed

    private void btnRegistrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProveedorActionPerformed
         
        
    }//GEN-LAST:event_btnRegistrarProveedorActionPerformed

    private void btnListarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProveedorActionPerformed
        ProveedoresListar listaProveedor = new ProveedoresListar();
        listaProveedor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnListarProveedorActionPerformed

    private void jBCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarSesionActionPerformed
       Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBCerrarSesionActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        if(jPaCerrarSesion.isVisible())
            jPaCerrarSesion.setVisible(false);
        else jPaCerrarSesion.setVisible(true);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnConsultasProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasProveedorActionPerformed
       if (bandera ==false){
        panelDocumentos.setVisible(true);
        bandera = true;
    }
    
    else{
         panelDocumentos.setVisible(false);
        bandera = false;
    }
    }//GEN-LAST:event_btnConsultasProveedorActionPerformed

    private void txtRucProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucProveedorActionPerformed
        //if txtRucProveedor.se
    }//GEN-LAST:event_txtRucProveedorActionPerformed

    private void txtRucProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRucProveedorMouseClicked
      //  txtRucProveedor.setText("");
    }//GEN-LAST:event_txtRucProveedorMouseClicked

    public void limpiar(){
        /*TextPrompt RUCProveedor = new TextPrompt("RUC del Proveedor", txtRucProveedor);
        TextPrompt RazonProveedor = new TextPrompt("Razón Social del Proveedor", txtRazonSocialProveedor);
        TextPrompt direccionProveedor = new TextPrompt("Dirección del Proveedor", txtDireccionProveedor);
        TextPrompt correoProveedor = new TextPrompt("Correo electronico del Proveedor", txtCorreoProveedor);
        TextPrompt telefonoProveedor = new TextPrompt("Telefóno del Proveedor", txtTelefonoProveedor);
        TextPrompt contactoProveedor = new TextPrompt("Persona de Contacto del Proveedor", txtPersonaContactoProveedor);
        */
        txtRucProveedor.setText("");
        txtRazonSocialProveedor.setText("");
        txtPersonaContactoProveedor.setText("");
        txtTelefonoProveedor.setText("");
        txtCorreoProveedor.setText("");
        txtDireccionProveedor.setText("");
    }
 
    
    private void btnRegistrarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProvActionPerformed
        
        String Ruc="";
        String RazonSocial="";
        String Direccion="";
        String telefono="";
        String contacto="";
        String correo="";    
        
        try{
        
        if (!(txtRucProveedor.getText().equals("RUC del Proveedor"))){
          Ruc = txtRucProveedor.getText();
           
        }
       if (!(txtRazonSocialProveedor.getText().equals("Razón Social del Proveedor"))){
            RazonSocial = txtRazonSocialProveedor.getText();
           
        }
       if (!(txtDireccionProveedor.getText().equals("Dirección del Proveedor"))){
            Direccion = txtDireccionProveedor.getText();
           
        }
        if (!(txtTelefonoProveedor.getText().equals("Teléfono del Proveedor"))){
           telefono = txtTelefonoProveedor.getText();
          
        }
        if (!(txtPersonaContactoProveedor.getText().equals("Persona de Contacto del Proveedor"))){
           contacto = txtPersonaContactoProveedor.getText();
           
        }
        if (!(txtCorreoProveedor.getText().equals("Correo Electronico del Proveedor"))){
           correo = txtPersonaContactoProveedor.getText();
           
        }
        
        if ((Ruc.isEmpty())||(RazonSocial.isEmpty())||(correo.isEmpty())||(Direccion.isEmpty())||(telefono.isEmpty())||(contacto.isEmpty())){
            JOptionPane.showMessageDialog(null, "Complete todos los campos ");
        }
        else if(!((Ruc.isEmpty())&&(RazonSocial.isEmpty())&&(correo.isEmpty())&&(Direccion.isEmpty())&&(telefono.isEmpty())&&(contacto.isEmpty()))){
            Lis.add(new Proveedor(Ruc,RazonSocial,Direccion,correo,telefono,contacto));
            JOptionPane.showMessageDialog(null, "Proveedor Registrado Exitosamente ");
            limpiar();
        }
        
        
        }
        catch(Exception e){
            
        }
       
        
       //String RazonSocial = txtRazonSocialProveedor.getText();
        
        
       // System.out.println(RazonSocial);
    }//GEN-LAST:event_btnRegistrarProvActionPerformed

    private void txtRucProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRucProveedorFocusGained
        
    }//GEN-LAST:event_txtRucProveedorFocusGained

    private void txtRucProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRucProveedorFocusLost
           
    }//GEN-LAST:event_txtRucProveedorFocusLost

    private void txtRazonSocialProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRazonSocialProveedorFocusGained
       
        
    }//GEN-LAST:event_txtRazonSocialProveedorFocusGained

    private void txtRazonSocialProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRazonSocialProveedorFocusLost
       
        
    }//GEN-LAST:event_txtRazonSocialProveedorFocusLost

    private void txtDireccionProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionProveedorFocusGained
      
        
    }//GEN-LAST:event_txtDireccionProveedorFocusGained

    private void txtDireccionProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionProveedorFocusLost
        
    }//GEN-LAST:event_txtDireccionProveedorFocusLost

    private void txtCorreoProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoProveedorFocusGained
        
    }//GEN-LAST:event_txtCorreoProveedorFocusGained

    private void txtCorreoProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoProveedorFocusLost
       
    }//GEN-LAST:event_txtCorreoProveedorFocusLost

    private void txtTelefonoProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoProveedorFocusGained
        
    }//GEN-LAST:event_txtTelefonoProveedorFocusGained

    private void txtTelefonoProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoProveedorFocusLost
       
    }//GEN-LAST:event_txtTelefonoProveedorFocusLost

    private void txtPersonaContactoProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPersonaContactoProveedorFocusGained
        
    }//GEN-LAST:event_txtPersonaContactoProveedorFocusGained

    private void txtPersonaContactoProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPersonaContactoProveedorFocusLost
        
    }//GEN-LAST:event_txtPersonaContactoProveedorFocusLost

    private void btnNotaCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotaCreditoActionPerformed
        InicioAdministra credito = new InicioAdministra();
        credito.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNotaCreditoActionPerformed

    private void btnFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturasActionPerformed
        ConsultasFacturas facturas = new ConsultasFacturas();
        facturas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnFacturasActionPerformed

    private void btnNotaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotaVentaActionPerformed
        ConsultarNotasVenta notasVenta = new ConsultarNotasVenta();
        notasVenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNotaVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProveedorRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProveedorRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProveedorRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProveedorRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProveedorRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultasProveedor;
    private javax.swing.JButton btnFacturas;
    private javax.swing.JButton btnListarProveedor;
    private javax.swing.JButton btnNotaCredito;
    private javax.swing.JButton btnNotaVenta;
    private javax.swing.JButton btnRegistrarProv;
    private javax.swing.JButton btnRegistrarProveedor;
    private javax.swing.JButton btnSalirProveedor;
    private javax.swing.JButton jBCerrarSesion;
    private javax.swing.JLabel jLSidimLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPEncabezado;
    private javax.swing.JPanel jPMod;
    private javax.swing.JPanel jPaCerrarSesion;
    private javax.swing.JLabel lblCorreoProveedor;
    private javax.swing.JLabel lblDireccionProveedor;
    private javax.swing.JLabel lblPersonaContacto;
    private javax.swing.JLabel lblRazonSocialProveedor;
    private javax.swing.JLabel lblRucProveedor;
    private javax.swing.JLabel lblTelefonoProveedor;
    private javax.swing.JPanel panelDocumentos;
    private javax.swing.JTextField txtCorreoProveedor;
    private javax.swing.JTextField txtDireccionProveedor;
    private javax.swing.JTextField txtPersonaContactoProveedor;
    private javax.swing.JTextField txtRazonSocialProveedor;
    private javax.swing.JTextField txtRucProveedor;
    private javax.swing.JTextField txtTelefonoProveedor;
    // End of variables declaration//GEN-END:variables
}
