/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesAdministración;

import Interfaces.ContribuyentesPrincipal;
import Interfaces.DeclaracionesInicio;
import InterfacesProveedor.ProveedorPrincipal;
import InterfacesReportes.ReportesPrincipal;

/**
 *
 * @author Bryan
 */
public class InicioAdminAccesos extends javax.swing.JFrame {

    /**
     * Creates new form InicioAdminAccesos
     */
    public InicioAdminAccesos() {
        initComponents();
        this.setSize(1366, 768);
        jBCerrarSesion.setVisible(false);
        btnHora.setVisible(false);
        jPHora.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPVer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrarProveedor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnListarProveedor = new javax.swing.JButton();
        btnConsultasProveedor = new javax.swing.JButton();
        btnConsultasProveedor1 = new javax.swing.JButton();
        btnConsultasProveedor2 = new javax.swing.JButton();
        btnConsultasProveedor3 = new javax.swing.JButton();
        btnHora = new javax.swing.JButton();
        jPEncabezado = new javax.swing.JPanel();
        jLSidimLogo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBCerrarSesion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPHora = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtBuscarUsuarios1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListadoUsuarios1 = new javax.swing.JTable();
        btnBuscarUsuarios1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPVer.setBackground(new java.awt.Color(51, 51, 51));
        jPVer.setForeground(new java.awt.Color(51, 51, 51));
        jPVer.setMaximumSize(new java.awt.Dimension(300, 200));
        jPVer.setPreferredSize(new java.awt.Dimension(300, 280));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 241));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Luis López");

        btnRegistrarProveedor.setBackground(new java.awt.Color(38, 35, 36));
        btnRegistrarProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarProveedor.setForeground(new java.awt.Color(240, 240, 241));
        btnRegistrarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosAdmini/Usuarios.png"))); // NOI18N
        btnRegistrarProveedor.setText("Usuarios");
        btnRegistrarProveedor.setBorderPainted(false);
        btnRegistrarProveedor.setFocusPainted(false);
        btnRegistrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProveedorActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/iconUser48x48.png"))); // NOI18N

        btnListarProveedor.setBackground(new java.awt.Color(38, 35, 36));
        btnListarProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnListarProveedor.setForeground(new java.awt.Color(240, 240, 241));
        btnListarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosAdmini/Usuarios.png"))); // NOI18N
        btnListarProveedor.setText("Contribuyentes");
        btnListarProveedor.setBorderPainted(false);
        btnListarProveedor.setFocusPainted(false);
        btnListarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProveedorActionPerformed(evt);
            }
        });

        btnConsultasProveedor.setBackground(new java.awt.Color(38, 35, 36));
        btnConsultasProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultasProveedor.setForeground(new java.awt.Color(240, 240, 241));
        btnConsultasProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosAdmini/proveedores.png"))); // NOI18N
        btnConsultasProveedor.setText("Proveedores");
        btnConsultasProveedor.setBorderPainted(false);
        btnConsultasProveedor.setFocusPainted(false);
        btnConsultasProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasProveedorActionPerformed(evt);
            }
        });

        btnConsultasProveedor1.setBackground(new java.awt.Color(38, 35, 36));
        btnConsultasProveedor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultasProveedor1.setForeground(new java.awt.Color(240, 240, 241));
        btnConsultasProveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosAdmini/AccesosAlSite.png"))); // NOI18N
        btnConsultasProveedor1.setText("Accesos al Sistema");
        btnConsultasProveedor1.setBorderPainted(false);
        btnConsultasProveedor1.setFocusPainted(false);
        btnConsultasProveedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasProveedor1ActionPerformed(evt);
            }
        });

        btnConsultasProveedor2.setBackground(new java.awt.Color(38, 35, 36));
        btnConsultasProveedor2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultasProveedor2.setForeground(new java.awt.Color(240, 240, 241));
        btnConsultasProveedor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosAdmini/reportes.png"))); // NOI18N
        btnConsultasProveedor2.setText("Reportes");
        btnConsultasProveedor2.setBorderPainted(false);
        btnConsultasProveedor2.setFocusPainted(false);
        btnConsultasProveedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasProveedor2ActionPerformed(evt);
            }
        });

        btnConsultasProveedor3.setBackground(new java.awt.Color(38, 35, 36));
        btnConsultasProveedor3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultasProveedor3.setForeground(new java.awt.Color(240, 240, 241));
        btnConsultasProveedor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosAdmini/declaraciones.png"))); // NOI18N
        btnConsultasProveedor3.setText("Declaraciones");
        btnConsultasProveedor3.setBorderPainted(false);
        btnConsultasProveedor3.setFocusPainted(false);
        btnConsultasProveedor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasProveedor3ActionPerformed(evt);
            }
        });

        btnHora.setBackground(new java.awt.Color(153, 153, 153));
        btnHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHora.setForeground(new java.awt.Color(240, 240, 241));
        btnHora.setText("Hora de acceso y salida");
        btnHora.setBorderPainted(false);
        btnHora.setFocusPainted(false);
        btnHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPVerLayout = new javax.swing.GroupLayout(jPVer);
        jPVer.setLayout(jPVerLayout);
        jPVerLayout.setHorizontalGroup(
            jPVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrarProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnListarProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
            .addComponent(btnConsultasProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConsultasProveedor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConsultasProveedor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConsultasProveedor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPVerLayout.createSequentialGroup()
                .addGroup(jPVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPVerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHora))
                    .addGroup(jPVerLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPVerLayout.setVerticalGroup(
            jPVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultasProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultasProveedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultasProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultasProveedor3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jPEncabezado.setBackground(new java.awt.Color(54, 112, 171));

        jLSidimLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProveedor/Logo.jpeg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hola Luis López");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPEncabezadoLayout = new javax.swing.GroupLayout(jPEncabezado);
        jPEncabezado.setLayout(jPEncabezadoLayout);
        jPEncabezadoLayout.setHorizontalGroup(
            jPEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEncabezadoLayout.createSequentialGroup()
                .addComponent(jLSidimLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 908, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPEncabezadoLayout.setVerticalGroup(
            jPEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLSidimLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jBCerrarSesion.setBackground(new java.awt.Color(0, 153, 51));
        jBCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBCerrarSesion.setForeground(new java.awt.Color(240, 240, 241));
        jBCerrarSesion.setText("Cerrar Sesión");
        jBCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1097, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(38, 35, 36));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Hora de accesos y salidas del sistema");

        txtBuscarUsuarios1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBuscarUsuarios1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarUsuarios1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarUsuarios1FocusLost(evt);
            }
        });

        tblListadoUsuarios1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombres", "Apellidos", "Usuario", "Fecha", "Hora de Ingreso", "Hora de Salida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListadoUsuarios1.getTableHeader().setReorderingAllowed(false);
        tblListadoUsuarios1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblListadoUsuarios1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblListadoUsuarios1FocusLost(evt);
            }
        });
        tblListadoUsuarios1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListadoUsuarios1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblListadoUsuarios1);

        btnBuscarUsuarios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProveedor/1490129321-rounded10_82180.png"))); // NOI18N
        btnBuscarUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarios1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPHoraLayout = new javax.swing.GroupLayout(jPHora);
        jPHora.setLayout(jPHoraLayout);
        jPHoraLayout.setHorizontalGroup(
            jPHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHoraLayout.createSequentialGroup()
                .addGroup(jPHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPHoraLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBuscarUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPHoraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(jPHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPHoraLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8)
                    .addContainerGap(562, Short.MAX_VALUE)))
        );
        jPHoraLayout.setVerticalGroup(
            jPHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPHoraLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarUsuarios1)
                    .addComponent(txtBuscarUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(jPHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPHoraLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(581, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jPHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1101, 1101, 1101)
                        .addComponent(jBCerrarSesion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPVer, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jBCerrarSesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPVer, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        jBCerrarSesion.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jBCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarSesionActionPerformed
        // TODO add your handling code here:
        Login salir = new Login();
        this.setVisible(false);
        salir.setVisible(true);
    }//GEN-LAST:event_jBCerrarSesionActionPerformed

    private void btnConsultasProveedor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasProveedor3ActionPerformed
        // TODO add your handling code here:
          DeclaracionesInicio declaraciones = new DeclaracionesInicio();
       declaraciones.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnConsultasProveedor3ActionPerformed

    private void btnConsultasProveedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasProveedor2ActionPerformed
       ReportesPrincipal p = new ReportesPrincipal();
       p.setVisible(true);
       this.setVisible(false);
        
    }//GEN-LAST:event_btnConsultasProveedor2ActionPerformed

    private void btnConsultasProveedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasProveedor1ActionPerformed
        // TODO add your handling code here:
        btnHora.setVisible(true);
    }//GEN-LAST:event_btnConsultasProveedor1ActionPerformed

    private void btnConsultasProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasProveedorActionPerformed
ProveedorPrincipal p = new ProveedorPrincipal();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnConsultasProveedorActionPerformed

    private void btnListarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProveedorActionPerformed
        // TODO add your handling code here:
          ContribuyentesPrincipal contribuyentes = new ContribuyentesPrincipal();
        contribuyentes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnListarProveedorActionPerformed

    private void btnRegistrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProveedorActionPerformed
        //lblBienvenido.setVisible(false);
        InicioAdminUsuarios usuarios = new InicioAdminUsuarios();
        usuarios.setVisible(true);
        usuarios.JPOUsuarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistrarProveedorActionPerformed

    private void btnHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoraActionPerformed
        // TODO add your handling code here:
        jPHora.setVisible(true);
    }//GEN-LAST:event_btnHoraActionPerformed

    private void txtBuscarUsuarios1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarUsuarios1FocusGained

    }//GEN-LAST:event_txtBuscarUsuarios1FocusGained

    private void txtBuscarUsuarios1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarUsuarios1FocusLost

    }//GEN-LAST:event_txtBuscarUsuarios1FocusLost

    private void tblListadoUsuarios1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblListadoUsuarios1FocusGained

    }//GEN-LAST:event_tblListadoUsuarios1FocusGained

    private void tblListadoUsuarios1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblListadoUsuarios1FocusLost

    }//GEN-LAST:event_tblListadoUsuarios1FocusLost

    private void tblListadoUsuarios1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListadoUsuarios1MouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_tblListadoUsuarios1MouseClicked

    private void btnBuscarUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarios1ActionPerformed
        
    }//GEN-LAST:event_btnBuscarUsuarios1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioAdminAccesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioAdminAccesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioAdminAccesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioAdminAccesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioAdminAccesos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarUsuarios1;
    private javax.swing.JButton btnConsultasProveedor;
    private javax.swing.JButton btnConsultasProveedor1;
    private javax.swing.JButton btnConsultasProveedor2;
    private javax.swing.JButton btnConsultasProveedor3;
    public javax.swing.JButton btnHora;
    private javax.swing.JButton btnListarProveedor;
    private javax.swing.JButton btnRegistrarProveedor;
    private javax.swing.JButton jBCerrarSesion;
    private javax.swing.JLabel jLSidimLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPEncabezado;
    private javax.swing.JPanel jPHora;
    private javax.swing.JPanel jPVer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblListadoUsuarios1;
    private javax.swing.JTextField txtBuscarUsuarios1;
    // End of variables declaration//GEN-END:variables
}
